[colors]
background = '#21272a'
foreground = '#ffffff'
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#21272a'

ansi = [
    '#343a3f',
    '#fa4d56',
    '#42be65',
    '#ff832b',
    '#4589ff',
    '#ff7eb6',
    '#3ddbd9',
    '#c1c7cd',
]
brights = [
    '#4d5358',
    '#ff8389',
    '#42be65',
    '#fddc69',
    '#78a9ff',
    '#ffb3b8',
    '#82cfff',
    '#dde1E6',
]

[colors.tab_bar]
background = "#000000"

[colors.tab_bar.active_tab]
bg_color = '#121619'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = "#21272a"
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#21272a'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Carburator Cool'
