[colors]
background = '#272525'
foreground = '#ffffff'
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#272525'

ansi = [
    '#3c3838',
    '#fa4d56',
    '#42be65',
    '#ff832b',
    '#4589ff',
    '#ff7eb6',
    '#3ddbd9',
    '#cac5c4',
]
brights = [
    '#565151',
    '#ff8389',
    '#42be65',
    '#fddc69',
    '#78a9ff',
    '#ffb3b8',
    '#82cfff',
    '#e5e0df',
]

[colors.tab_bar]
background = "#000000"

[colors.tab_bar.active_tab]
bg_color = '#171414'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = "#272525"
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#272525'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Carburator Warm'
