[colors]
background = '#262626'
foreground = '#ffffff'
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#262626'

ansi = [
    '#393939',
    '#fa4d56',
    '#42be65',
    '#ff832b',
    '#4589ff',
    '#ff7eb6',
    '#3ddbd9',
    '#c6c6c6',
]
brights = [
    '#525252',
    '#ff8389',
    '#42be65',
    '#fddc69',
    '#78a9ff',
    '#ffb3b8',
    '#82cfff',
    '#e0e0e0',
]

[colors.tab_bar]
background = "rgb(22,22,22,0.8)"

[colors.tab_bar.active_tab]
bg_color = '#262626'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = "rgb(22,22,22,0.8)"
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#262626'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Carburator Medium'
